// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, isHeroku;

  console.log("app node file", process.cwd());

  express = require('express');

  app = express();

  app.use(express["static"](__dirname + '/public'));

  exports.startServer = function(port, path, callback) {
    var io, p, server;
    p = process.env.PORT || port;
    app.get('/', function(req, res) {
      return res.sendfile('./public/index.html');
    });
    server = app.listen(p);
    io = require('socket.io').listen(server);
    return console.log('Listening on port:' + p);
  };

  isHeroku = process.env.IS_HEROKU;

  if (isHeroku) {
    exports.startServer();
  }

}).call(this);
