// Generated by CoffeeScript 1.6.3
(function() {
  if (this.SpaceBees == null) {
    this.SpaceBees = {};
  }

  if (SpaceBees.Routers == null) {
    SpaceBees.Routers = {};
  }

  if (SpaceBees.Views == null) {
    SpaceBees.Views = {};
  }

  if (SpaceBees.Models == null) {
    SpaceBees.Models = {};
  }

  if (SpaceBees.Collections == null) {
    SpaceBees.Collections = {};
  }

  require('lib/helpers');

  require('routers/main');

  $(function() {
    var LauncherView;
    Backbone.history.start({
      pushState: true
    });
    LauncherView = require('views/launcher');
    return SpaceBees.Views.Launcher = new LauncherView();
  });

}).call(this);
