// Generated by CoffeeScript 1.6.3
(function() {
  var Entity, Missile,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = require('./entity');

  module.exports = Missile = (function(_super) {
    __extends(Missile, _super);

    function Missile(connection, server, data) {
      this.connection = connection;
      this.server = server;
      this.getState = __bind(this.getState, this);
      Missile.__super__.constructor.call(this, connection.id, "", "", data.x, data.y, data.z);
    }

    Missile.prototype.getState = function() {
      return {
        'id': this.id,
        'type': this.type,
        'x': this.x,
        'y': this.y,
        'z': this.z
      };
    };

    return Missile;

  })(Entity);

}).call(this);
