// Generated by CoffeeScript 1.6.3
(function() {
  var AuthModel, Facebook, utils,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  utils = require('lib/utils');

  AuthModel = require('models/auth');

  Facebook = (function(_super) {
    __extends(Facebook, _super);

    Facebook.prototype.status = null;

    Facebook.prototype.accessToken = null;

    Facebook.prototype.model = new AuthModel();

    function Facebook(options) {
      this.options = options;
      this.processUserData = __bind(this.processUserData, this);
      this.processComment = __bind(this.processComment, this);
      this.processLike = __bind(this.processLike, this);
      this.facebookLogout = __bind(this.facebookLogout, this);
      this.publishAbortionResult = __bind(this.publishAbortionResult, this);
      this.loginHandler = __bind(this.loginHandler, this);
      this.triggerLogin = __bind(this.triggerLogin, this);
      this.loginStatusHandler = __bind(this.loginStatusHandler, this);
      this.getLoginStatus = __bind(this.getLoginStatus, this);
      this.saveAuthResponse = __bind(this.saveAuthResponse, this);
      this.sdkLoadHandler = __bind(this.sdkLoadHandler, this);
      console.debug('Facebook#constructor');
      _(this).extend(_.Deferred());
      utils.deferMethods({
        deferred: this,
        methods: ['parse', 'subscribe', 'postToGraph', 'getAccumulatedInfo', 'getInfo', 'getLoginStatus'],
        onDeferral: this.loadSDK
      });
      utils.wrapAccumulators(this, ['getAccumulatedInfo']);
    }

    Facebook.prototype.dispose = function() {};

    Facebook.prototype.loadSDK = function() {
      console.debug('Facebook#loadSDK');
      if (this.state() === 'resolved' || this.loading) {
        return;
      }
      this.loading = true;
      window.fbAsyncInit = this.sdkLoadHandler;
      return utils.loadLib('http://connect.facebook.net/en_US/all.js', null, this.reject);
    };

    Facebook.prototype.sdkLoadHandler = function() {
      var error;
      console.debug('Facebook#sdkLoadHandler');
      this.loading = false;
      try {
        delete window.fbAsyncInit;
      } catch (_error) {
        error = _error;
        window.fbAsyncInit = void 0;
      }
      FB.init({
        appId: this.options.appId,
        status: true,
        cookie: true,
        xfbml: false
      });
      this.registerHandlers();
      console.debug('Facebook#sdkLoadHandler: resolve');
      return this.resolve();
    };

    Facebook.prototype.registerHandlers = function() {
      return this.subscribe('auth.logout', this.facebookLogout);
    };

    Facebook.prototype.isLoaded = function() {
      return Boolean(window.FB && FB.login);
    };

    Facebook.prototype.saveAuthResponse = function(response) {
      var authResponse;
      console.debug('Facebook#saveAuthResponse', response);
      this.status = response.status;
      authResponse = response.authResponse;
      if (authResponse) {
        return this.accessToken = authResponse.accessToken;
      } else {
        return this.accessToken = null;
      }
    };

    Facebook.prototype.getLoginStatus = function(callback, force) {
      if (callback == null) {
        callback = this.loginStatusHandler;
      }
      if (force == null) {
        force = false;
      }
      console.debug('Facebook#getLoginStatus', this.state());
      return FB.getLoginStatus(callback, force);
    };

    Facebook.prototype.loginStatusHandler = function(response) {
      var authResponse;
      console.debug('Facebook#loginStatusHandler', response);
      this.saveAuthResponse(response);
      authResponse = response.authResponse;
      if (authResponse) {
        this.publishSession(authResponse);
        return this.getUserData();
      } else {
        return this.trigger('logout');
      }
    };

    Facebook.prototype.triggerLogin = function(loginContext) {
      console.debug('Facebook#triggerLogin', loginContext);
      return FB.login(_(this.loginHandler).bind(this, loginContext), {
        scope: this.options.scope
      });
    };

    Facebook.prototype.loginHandler = function(loginContext, response) {
      var authResponse;
      console.debug('Facebook#loginHandler', loginContext, response);
      this.saveAuthResponse(response);
      authResponse = response.authResponse;
      if (authResponse) {
        this.trigger('loginSuccessful', {
          provider: this
        });
        this.publishSession(authResponse);
        return this.getUserData();
      } else {
        this.trigger('loginAbort', {
          provider: this
        });
        return this.getLoginStatus(this.publishAbortionResult, true);
      }
    };

    Facebook.prototype.publishSession = function(authResponse) {
      console.debug('Facebook#publishSession', authResponse);
      return this.trigger('serviceProviderSession', {
        provider: this,
        userId: authResponse.userID,
        accessToken: authResponse.accessToken
      });
    };

    Facebook.prototype.publishAbortionResult = function(response) {
      var authResponse;
      this.saveAuthResponse(response);
      authResponse = response.authResponse;
      if (authResponse) {
        this.trigger('loginSuccessful', {
          provider: this
        });
        this.trigger('loginSuccessfulThoughAborted', {
          provider: this,
          loginContext: loginContext
        });
        return this.publishSession(authResponse);
      } else {
        return this.trigger('loginFail', {
          provider: this
        });
      }
    };

    Facebook.prototype.facebookLogout = function(response) {
      console.debug('Facebook#facebookLogout', response);
      return this.saveAuthResponse(response);
    };

    Facebook.prototype.logout = function() {
      return this.status = this.accessToken = null;
    };

    Facebook.prototype.processLike = function(url) {
      console.debug('Facebook#processLike', url);
      return this.trigger('facebookLike', url);
    };

    Facebook.prototype.processComment = function(comment) {
      console.debug('Facebook#processComment', comment, comment.href);
      return this.trigger('facebookComment', comment.href);
    };

    Facebook.prototype.parse = function(el) {
      return FB.XFBML.parse(el);
    };

    Facebook.prototype.subscribe = function(eventType, handler) {
      return FB.Event.subscribe(eventType, handler);
    };

    Facebook.prototype.unsubscribe = function(eventType, handler) {
      return FB.Event.unsubscribe(eventType, handler);
    };

    Facebook.prototype.postToGraph = function(ogResource, data, callback) {
      return FB.api(ogResource, 'post', data, function(response) {
        console.debug('Facebook#postToGraph callback', response);
        if (callback) {
          return callback(response);
        }
      });
    };

    Facebook.prototype.postToStream = function(data, callback) {
      console.debug('Facebook.postToStream', data);
      return this.postToGraph('/me/feed', data, callback);
    };

    Facebook.prototype.getAccumulatedInfo = function(urls, callback) {
      console.debug('Facebook#getAccumulatedInfo', urls, callback);
      if (typeof urls === 'string') {
        urls = [urls];
      }
      urls = _(urls).reduce(function(memo, url) {
        if (memo) {
          memo += ',';
        }
        return memo += encodeURIComponent(url);
      }, '');
      return FB.api("?ids=" + urls, callback);
    };

    Facebook.prototype.getInfo = function(id, callback) {
      return FB.api(id, callback);
    };

    Facebook.prototype.getUserData = function() {
      console.debug('Facebook#getUserData');
      return this.getInfo('/me', this.processUserData);
    };

    Facebook.prototype.processUserData = function(response) {
      console.debug('Facebook#processUserData', response);
      this.model.save({
        'username': response.name,
        'password': '',
        'firstName': response.first_name,
        'lastName': response.last_name,
        'uid': response.id
      });
      console.log('model saved');
      return this.trigger('userData', response);
    };

    return Facebook;

  })(Backbone.View);

  module.exports = Facebook;

}).call(this);
