// Generated by CoffeeScript 1.6.3
(function() {
  var GameView, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = GameView = (function(_super) {
    __extends(GameView, _super);

    function GameView() {
      this.render = __bind(this.render, this);
      this.initialize = __bind(this.initialize, this);
      _ref = GameView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    GameView.prototype.className = 'game';

    GameView.prototype.el = 'div#game';

    GameView.prototype.template = require('views/templates/game');

    GameView.prototype.initialize = function() {
      this.render();
    };

    GameView.prototype.render = function() {
      return this.$el.html(this.template);
    };

    return GameView;

  })(Backbone.View);

}).call(this);
