// Generated by CoffeeScript 1.6.3
(function() {
  var AuthModel, FacebookView, Game, GameView, LauncherView, Loader, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Game = require('models/game');

  GameView = require('views/game');

  Loader = require('lib/loader');

  FacebookView = require('views/facebook');

  AuthModel = require('models/auth');

  module.exports = LauncherView = (function(_super) {
    __extends(LauncherView, _super);

    function LauncherView() {
      this.initialize = __bind(this.initialize, this);
      _ref = LauncherView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    LauncherView.prototype.className = 'launcher';

    LauncherView.prototype.template = require('views/templates/launcher');

    LauncherView.prototype.el = 'div#launcher';

    LauncherView.prototype.events = {
      "click .btn-success": "startGame",
      "click .fb-signup": "login"
    };

    LauncherView.prototype.initialize = function() {
      this.facebook = new FacebookView({
        appId: '154939177928888',
        scope: 'email'
      });
      this.facebook.loadSDK();
      this.render();
      return this.facebook.getLoginStatus();
    };

    LauncherView.prototype.render = function() {
      this.$el.html(this.template);
      return $(function() {
        var BV;
        BV = new $.BigVideo();
        BV.init();
        return BV.show('backgroundMovie.mp4', {
          ambient: true
        });
      });
    };

    LauncherView.prototype.login = function(event) {
      return this.facebook.triggerLogin("loginbutton");
    };

    LauncherView.prototype.startGame = function(event) {
      var progress,
        _this = this;
      this.$el.hide();
      $('#big-video-vid').remove();
      SpaceBees.Views.Game = new GameView();
      window.game = SpaceBees.Models.Game = new Game();
      progress = document.getElementById('progress');
      SpaceBees.Loader = new Loader({
        onLoad: function() {
          console.log("All Loaded");
          window.socket = new io.connect(window.location.hostname);
          progress.innerText = "Connecting to Server...";
          return window.socket.on('client_id', function(client_id) {
            SpaceBees.Models.Game.start(client_id);
            return progress.innerText = "Click to Play!";
          });
        },
        onError: function(s) {
          return console.log("Error on " + s);
        },
        onProgress: function(p, t, n) {
          return progress.innerText = Math.floor(p.loaded / p.total * 100) + "%";
        }
      });
      return SpaceBees.Loader.load({
        textures: {
          'missile': 'textures/missiles/hellfire_skin.png',
          'scrapers1.diffuse': 'textures/scrapers1/diffuse.jpg',
          'scrapers2.diffuse': 'textures/scrapers2/diffuse.jpg',
          'chipmetal': 'textures/terrain/chipmetal/texturemap.jpg',
          'missile_particle': 'textures/missiles/particle.png'
        },
        texturesCube: {
          'interstellar': "textures/skybox/interstellar/%1.jpg"
        },
        geometries: {
          'missile': 'models/missiles/hellfire.js',
          'ship': 'models/spaceship_0.js',
          'scrapers1': 'models/scrapers1.js',
          'scrapers2': 'models/scrapers2.js',
          'bee': 'models/bee.js',
          'city': 'models/city/city.js'
        },
        analysers: {},
        images: {
          'cursor': 'images/cursor.png',
          'aim': 'images/aim.png',
          'target_lock': 'images/lock.png'
        }
      });
    };

    return LauncherView;

  })(Backbone.View);

}).call(this);
