// Generated by CoffeeScript 1.6.3
(function() {
  var ServerlistView, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = ServerlistView = (function(_super) {
    __extends(ServerlistView, _super);

    function ServerlistView() {
      _ref = ServerlistView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ServerlistView.prototype.className = 'serverlist';

    ServerlistView.prototype.el = 'body.serverlist';

    ServerlistView.prototype.template = require('views/templates/serverlist');

    ServerlistView.prototype.render = function() {
      return this.el.html(template);
    };

    return ServerlistView;

  })(Backbone.View);

}).call(this);
